version: '3.9'

services:
  # Frontend Service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: cms-frontend
    ports:
      - "8085:80"
    env_file:
      - /envs/cms-frontend.env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - cms-network
      - reverse-proxy

  # Backend Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cms-backend
    ports:
      - "5005:5000"
    env_file:
      - /envs/cms-backend.env
    volumes:
      - ./server/uploads:/app/uploads
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - cms-network
      - reverse-proxy

  # MySQL Database Service (Optional - if you're using MySQL)
  mysql:
    image: mysql:8.0
    container_name: cms-mysql
    ports:
      - "3309:3306"
    env_file:
      - /envs/cms-mysql.env
    command
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/database:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - cms-network
      - reverse-proxy

networks:
  cms-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local